name: '[Demo] Build and Test 5_testing, Basic'

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'      
        java-version: '17'

    - name: Build Parent POM
      run: mvn -B --update-snapshots --file 1_maven/demo/parent/pom.xml install

    - name: Build with Maven
      run: mvn -T1C -B --update-snapshots --file 5_testing/demo/pom.xml verify
      
    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1
